import test from 'node:test';
import assert from 'node:assert/strict';
import { FPSControls } from '../dist/controls.js';
import { movePlayer } from '../dist/movement.js';
class Events{listeners={};addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}emit(name,props={}){for(const fn of this.listeners[name]??[])fn({preventDefault(){},...props});}}
function setup(){const doc=new Events(),win=new Events(),canvas=new Events();let starts=0,pauses=0,errors=0,requests=0;canvas.requestPointerLock=()=>{requests++;};doc.exitPointerLock=()=>{doc.pointerLockElement=null;doc.emit('pointerlockchange');};const c=new FPSControls(canvas,{document:doc,window:win,onStart:()=>starts++,onPause:()=>pauses++,onError:()=>errors++});return {c,doc,win,canvas,counts:()=>({starts,pauses,errors,requests}),lock(){doc.pointerLockElement=canvas;doc.emit('pointerlockchange');}};}
test('deployment requests capture synchronously; simulation waits for capture',()=>{const t=setup();t.c.request();assert.equal(t.counts().requests,1);assert.equal(t.counts().starts,0);t.lock();assert.equal(t.counts().starts,1);assert.equal(t.c.locked,true);});
test('capture denial never starts gameplay',()=>{const t=setup();t.c.request();t.doc.emit('pointerlockerror');assert.equal(t.counts().starts,0);assert.equal(t.counts().errors,1);assert.equal(t.c.pending,false);});
test('Escape clears held fire, aim and movement and pauses only once',()=>{const t=setup();t.c.request();t.lock();t.win.emit('keydown',{code:'KeyW'});t.doc.emit('mousedown',{button:0});t.doc.emit('mousedown',{button:2});t.win.emit('keydown',{code:'Escape'});assert.equal(t.counts().pauses,1);assert.equal(t.c.firing,false);assert.equal(t.c.aiming,false);assert.equal(t.c.keys.size,0);});
test('relative aim is proportional, unaffected by event batching, and pitch limited',()=>{const a=setup(),b=setup();a.c.request();a.lock();b.c.request();b.lock();for(let i=0;i<10;i++)a.doc.emit('mousemove',{movementX:10,movementY:3});b.doc.emit('mousemove',{movementX:100,movementY:30});assert.ok(Math.abs(a.c.yaw-b.c.yaw)<1e-12);assert.ok(Math.abs(a.c.pitch-b.c.pitch)<1e-12);for(let i=0;i<10;i++)a.c.look(0,900);assert.ok(a.c.pitch>-Math.PI/2);});
test('blur releases controls; unlocked mouse motion does not aim',()=>{const t=setup();t.c.request();t.lock();t.win.emit('blur');t.doc.emit('mousemove',{movementX:100,movementY:100});assert.equal(t.c.yaw,0);assert.equal(t.counts().pauses,1);});
const floor={minX:-100,maxX:100,minZ:-100,maxZ:100,minY:-1,maxY:0};
const player=()=>({pos:{x:0,y:1.7,z:0},vy:0,ground:true});
function run(p,keys,solids,seconds=1,hz=120){for(let i=0;i<seconds*hz;i++)movePlayer(p,new Set(keys),0,1/hz,solids);return p;}
test('diagonal movement has the same speed as forward movement',()=>{const a=run(player(),['KeyW'],[floor]);const b=run(player(),['KeyW','KeyD'],[floor]);assert.ok(Math.abs(Math.hypot(a.pos.x,a.pos.z)-Math.hypot(b.pos.x,b.pos.z))<1e-9);});
test('walk speed is stable at different simulation rates',()=>{const a=run(player(),['KeyW'],[floor],2,30),b=run(player(),['KeyW'],[floor],2,120);assert.ok(Math.abs(a.pos.z-b.pos.z)<1e-8);});
test('thin walls block movement even with a large timestep',()=>{const p=player();const wall={minX:1,maxX:1.1,minZ:-2,maxZ:2,minY:0,maxY:4};movePlayer(p,new Set(['KeyD']),0,.5,[floor,wall]);assert.ok(p.pos.x<.65);});
test('stairs use exact step heights, then remain stable on the platform',()=>{const steps=[1,2,3,4,5,6].map((n)=>({minX:n-1,maxX:n,minZ:-2,maxZ:2,minY:0,maxY:n*.5}));const platform={minX:6,maxX:12,minZ:-2,maxZ:2,minY:0,maxY:3};const p=player();p.pos.x=-1;run(p,['KeyD'],[floor,...steps,platform],1.5);assert.ok(Math.abs(p.pos.y-4.7)<1e-8);assert.equal(p.ground,true);assert.ok(p.pos.x>6);});
test('jump lands and ceiling blocks upward movement',()=>{const p=player();movePlayer(p,new Set(['Space']),0,1/120,[floor]);assert.ok(p.vy>0);run(p,[],[floor],2);assert.equal(p.pos.y,1.7);assert.equal(p.ground,true);const ceiling={minX:-2,maxX:2,minZ:-2,maxZ:2,minY:2.2,maxY:3};const q=player();movePlayer(q,new Set(['Space']),0,1/120,[floor,ceiling]);for(let i=0;i<60;i++){movePlayer(q,new Set(),0,1/120,[floor,ceiling]);assert.ok(q.pos.y<=2.2);}});
test('late mouse capture after blur cannot resume the game',()=>{const t=setup();t.c.request();t.win.emit('blur');t.lock();assert.equal(t.counts().starts,0);assert.equal(t.c.locked,false);});
